# Use Python 3.10 as the base image
FROM python:3.10

# Define /app as root directory
WORKDIR /app

# Copy the necessary files to the working directory
COPY requirements.txt .
COPY tox.ini .
COPY src ./src
COPY tests ./tests

# Install python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set run command
CMD ["streamlit", "run", "src/main.py"]
