version: '3.8'

services:
  spark_env:
    image: apache/spark-py:v3.4.0
    volumes:
      - /etc/java-11-openjdk/security:/java_security  # Mount java security files
    container_name: spark_env
    command: echo This was the JAVA_HOME $JAVA_HOME

  book-app:
    build:
      context: .
      dockerfile: Dockerfile.Python
    depends_on:
      - spark_env
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - /usr/lib/jvm/java-11-openjdk-amd64:/usr/lib/jvm/java-11-openjdk-amd64  # Getting the java home
      - /etc/java-11-openjdk/security:/usr/lib/jvm/java-11-openjdk-amd64/conf/security  # Mount java security files
    environment:
      - PYTHONPATH=/app
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    container_name: book-app
