version: '3.8'

services:
  book-app:
    build:
      context: .
      dockerfile: Dockerfile.Python
    depends_on:
      - spark_env
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./utils:/app/utils
    environment:
      - PYTHONPATH=/app
      # - JAVA_HOME=/opt/java/openjdk
    container_name: book-app

  spark_env:
    build:
      context: .
      dockerfile: Dockerfile.Spark
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./utils:/app/utils
    environment:
      SPARK_HOME: /opt/spark
      PATH: $PATH:/opt/spark/bin
      # JAVA_HOME: /opt/java/openjdk
    container_name: spark_env
    command: tail -f /dev/null
